version: '3'

services:

# ----------- Database --------------
  mysql-dev:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: mysql-docker-password
      MYSQL_DATABASE: docker-test-db
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"

  myclient:
    image: mysql:8.0.23
    depends_on:
      - mysql-dev
    command: mysql -uroot -pmysql-docker-password -hmysql-dev docker-test-db

  adminer:
    image: adminer
    ports:
      - 8050:8080

# ----------- Grafana --------------
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    user: root
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./data/prometheus/data:/prometheus"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
    user: root
    depends_on:
      - prometheus

# ----------- Kafka  --------------
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper-container
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kakfa
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-container:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
